FROM php:7.2-fpm

RUN apt-get update \
    && apt-get install -y libzip-dev git mariadb-client libmagickwand-dev curl --no-install-recommends

RUN docker-php-ext-install zip \
    && pecl install imagick \
    && docker-php-ext-enable imagick \
    && php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" \
    && php composer-setup.php \
    && php -r "unlink('composer-setup.php');" \
    && mv composer.phar /usr/local/bin/composer

RUN apt-get install -y libpq-dev \
    && docker-php-ext-configure pgsql -with-pgsql=/usr/local/pgsql \
    && docker-php-ext-install pdo pdo_pgsql pgsql


COPY . .
RUN composer install