# Use root/example as user/password credentials
version: '3'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: example
      POSTGRES_PASSWORD: example
      POSTGRES_DB: example
  
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    depends_on: 
      - db
    volumes: 
      - /var/www/html/vendor
      - ./:/var/www/html/
    environment:
      DB_CONNECTION: pgsql
      DB_DATABASE: example
      DB_USERNAME: example
      DB_PASSWORD: example
      APP_DEBUG: "true"
      DB_HOST: db
      APP_KEY: base64:uQJI5jjXeXFgCL2IDD4ssn/+aEtdxcm0ZNgRk+QSNwY=
    ports: 
      - 8000:8000