# Use root/example as user/password credentials
version: '3'

services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: example
  
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    depends_on: 
      - db
    volumes: 
      - /var/www/html/vendor
      - ./:/var/www/html/
    environment:
      DB_DATABASE: example
      DB_USERNAME: root
      DB_PASSWORD: example
      DB_HOST: db
      APP_KEY: base64:oWXfgthuF5BFwkux+9O45dN62jFdjEZSCxqYL+U88hM=
    ports: 
      - 8000:8000