version: "3"
services:
  nginx:
    depends_on:
      - api
      - client
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "80:80"
  api:
    build:
      dockerfile: Dockerfile
      context: ./server
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      - DB_USER=doadmin
      - DB_HOST=db-mysql-nyc1-05168-do-user-4729308-0.a.db.ondigitalocean.com
      - DB_DATA=defaultdb
      - DB_PASS=x95vxxp85j1adlwf
      - DB_PORT=25060
    restart: on-failure
  client:
    build:
      dockerfile: Dockerfile
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
