version: "3"
services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: example
  api:
    depends_on: 
      - db
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    volumes:
      - /app/node_modules
      - ./server:/app
    restart: always
    ports: 
      - 5000:5000
    environment:
      - DB_USER=root
      - DB_HOST=db
      - DB_DATA=example
      - DB_PASS=example
  client:
    network_mode: host
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
    